"""
Django settings for kxwheels project.

Generated by 'django-admin startproject' using Django 1.8.18.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import smtplib
from django.db import connections
from django.db.utils import OperationalError

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'j%us@1$4jfup*ffvf757ybk4!5!9s90z$x4ygl8#!iw&6c^sh&')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'paypal.standard',
    'paypal.pro',
    'paypal.standard.ipn',

    'haystack',
    'registration',
    'crequest',
    'sorl.thumbnail',
    'markdown_deux',

    'kxwheels.apps.account',
    'kxwheels.apps.l10n',
    'kxwheels.apps.shop',
    'kxwheels.apps.search',
    'kxwheels.apps.remittance',
    'kxwheels.apps.shipping',
    'kxwheels.apps.kx',
    'kxwheels.apps.reviews',
    'kxwheels.apps.vehicle',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',

    'crequest.middleware.CrequestMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
)

ROOT_URLCONF = 'kxwheels.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, '..', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kxwheels.context_processors.api_access_key',
                'kxwheels.context_processors.selected_vehicle',
            ],
        },
    },
]

WSGI_APPLICATION = 'kxwheels.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DATABASE_NAME'),
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': '5432',
    }
}
# db_conn = connections['default']
# try:
#     c = db_conn.cursor()
# except OperationalError:
#     connected = False
# else:
#     connected = True


#PAYPAL
PAYPAL_TEST = True


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = 'https://kxwheels.s3.amazonaws.com/'

# Customizations below
PROJECT_NAME = "KX Wheels"

SITE_ID = 1

IMPORT_WHEEL = 'Home/Documents/djangoprojects/kxwheels/imported_wheels/'

IMPORT_TIRE = '/srv/kxwheels/project/imported_tires/'

STATIC_ROOT = '/media/kxwheels/static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', 'static'),
]

AUTHENTICATION_BACKENDS = (
    "kxwheels.apps.account.backends.Custom.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
)

if not DEBUG:
    PREPEND_WWW = True

IGNORABLE_404_ENDS = ('favicon.ico', 'robots.txt',)
IGNORABLE_404_STARTS = ('',)
LOGIN_REDIRECT_URL = '/'

# Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

# Haystack
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://127.0.0.1:8080/solr'
    },
}


# Email
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_PASSWORD = 'Bugs123!@#' #my gmail password
EMAIL_HOST_USER = 'usman4ags@gmail.com' #my gmail username
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Django storages
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
AWS_ACCESS_KEY_ID = os.environ.get('AWS_CLIENT_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_CLIENT_SECRET')
AWS_STORAGE_BUCKET_NAME = 'kxwheels'
AWS_S3_SECURE_URLS = True

# Shipping
SHIPPING_MODULES = ('loomis',)

# Self API Access
API_ACCESS_KEY = "F2A53B2CF070457086347CABC4BDF4E6"

ADMIN_EMAIL = 'nav@navaulakh.com'

ROLLBAR = {
    'access_token': os.environ.get('ROLLBAR_API_KEY'),
    'environment': 'development' if DEBUG else 'production',
    'branch': 'default',
    'root': '/srv/kxwheels/project/',
}
